# Generated by Django 4.1.4 on 2023-01-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_staffed', models.BooleanField(default=False)),
                ('title', models.CharField(choices=[('TL', 'Team Lead'), ('MID', 'Mid Lead'), ('JUN', 'Junior')], default='j', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer Not Say')], default='n', max_length=50)),
                ('salary', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='personnel.department')),
            ],
        ),
    ]
